@alterar
Dado(/^eu estou no site orangehrm$/) do
	visit "http://opensource.demo.orangehrmlive.com/)"
end

Quando(/^eu altero o cadastro do empregado$/) do
  fill_in('txtUsername', :with => 'admin')
  fill_in('txtPassword', :with => 'admin')
  click_button('btnLogin')
  click_link('menu_pim_viewPimModule')
  click_link('Employee List')
  sleep 3
  fill_in('empsearch_id', :with => '0010')
  click_button('Search')
  click_link('0010')
  click_button('Edit')
  fill_in('personal_txtEmpFirstName', :with => 'Andre')
  fill_in('personal_txtEmpMiddleName', :with => 'Luiz')
  fill_in('personal_txtEmpLastName', :with => 'Silva')
  fill_in('personal_txtOtherID', :with => '25463')
  fill_in('personal_txtLicenNo', :with => '2576534')
  fill_in('personal_txtLicExpDate', :with => '2017-05-19')
  find(:xpath,'//*[@id="personal_optGender_1"]').click
  select('Brazil',:from =>'personal_cmbNation')
  select('Single',:from =>'personal_cmbMarital')
  fill_in('personal_DOB', :with => '1993-03-17')
  click_button('btnSave')
  click_link('Contact Details')
  click_button('Edit')
  fill_in('contact_street1', :with => 'Aimbere')
  fill_in('contact_city', :with => 'São Paulo')
  fill_in('contact_province', :with => 'São Paulo')
  fill_in('contact_emp_zipcode', :with => '05018010')
  select('Brazil',:from =>'contact_country')
  fill_in('contact_emp_hm_telephone', :with => '(11)3656-9879')
  fill_in('contact_emp_mobile', :with => '(11)97956-9248')
  fill_in('contact_emp_work_telephone', :with => '(11)3656-7890')
  fill_in('contact_emp_work_email', :with => 'teste@gmail.com')
  fill_in('contact_emp_oth_email', :with => 'mudandoemail@gmail.com')
  click_link('Emergency Contacts')
  click_link('Alda da Silva')
  fill_in('emgcontacts_name', :with => 'Alda da Silva')
  fill_in('emgcontacts_relationship', :with => 'Mae')
  fill_in('emgcontacts_homePhone', :with => '(11)3656-7890')
  fill_in('emgcontacts_mobilePhone', :with => '(11)97956-9867')
  fill_in('emgcontacts_workPhone', :with => '(11)97956-9867')
  click_button('Save')
  click_link('Dependents')
  click_link('Alda da Silva')
  fill_in('dependent_name', :with => 'Alda da Silva')
  select('Other',:from =>'dependent_relationshipType')
  fill_in('dependent_relationship', :with => 'Mae')
  fill_in('dependent_dateOfBirth', :with => '1993-03-17')
  click_button('Save')
  click_link('Immigration')
  click_link('Passport')
  fill_in('immigration_number', :with => '3652784234')
  fill_in('immigration_passport_issue_date', :with => '2000-05-19')
  fill_in('immigration_passport_expire_date', :with => '2020-02-20')
  fill_in('immigration_i9_status', :with => 'Approved')
  select('Brazil',:from =>'immigration_country')
  fill_in('immigration_i9_review_date', :with => '2018-05-17')
  fill_in('immigration_comments', :with => 'Por favor, gostaria muito de aprender mais sobre automatização! ;)')
  click_button('Save')
  click_link('Job')
  click_button('Edit')
  select('CEO',:from =>'job_job_title')
  select('Full-Time Contract',:from =>'job_emp_status')
  select('Professionals',:from =>'job_eeo_category')
  fill_in('job_joined_date', :with => '2017-02-20')
  select('IT',:from =>'job_sub_unit')
  select('New York Sales Office',:from =>'job_location')
  fill_in('job_contract_start_date', :with => '2017-02-20')
  click_button('Save')
  click_link('Salary')
  click_link('10.000,00')
  select('Executive',:from =>'salary_sal_grd_code')
  fill_in('salary_salary_component', :with => '10.000,00')
  select('Weekly',:from =>'salary_payperiod_code')
  select('United States Dollar',:from =>'salary_currency_id')
  fill_in('salary_basic_salary', :with => '70000')
  fill_in('salary_comments', :with => 'Será que estou indo bem?!')
  click_button('Save')
  click_link('Report-to')
  click_link('Fiona Grace')
  select('Indirect',:from =>'reportto_reportingMethodType')
  click_button('Save')
  click_link('Jasmine Morgan')
  select('Direct',:from =>'reportto_reportingMethodType')
  click_button('Save')
  click_link('Qualifications')
  click_link('Inmetrics')
  fill_in('experience_employer', :with => 'Santander')
  fill_in('experience_jobtitle', :with => 'Automação')
  fill_in('experience_from_date', :with => '2010-08-20')
  fill_in('experience_to_date', :with => '2016-03-10')
  fill_in('experience_comments', :with => 'Estamos quase acabando!')
  click_button('Save')
  
end

Então(/^a alteração é salva$/) do
  has_xpath?('//*[@id="sectionWorkExperience"]/div[2]/script')
  end