@criar
Dado(/^que eu estou no site orangehrm$/) do
	visit "http://opensource.demo.orangehrmlive.com/)"
end

Quando(/^eu cadastro o empregado$/) do
  fill_in('txtUsername', :with => 'admin')
  fill_in('txtPassword', :with => 'admin')
  click_button('btnLogin')
  click_link('menu_pim_viewPimModule')
  click_link('Add Employee')
  fill_in('firstName', :with => 'Amanda')
  fill_in('middleName', :with => 'Luiz')
  fill_in('lastName', :with => 'Silva')
  #fill_in('employeeId', :with => '02')
  check('chkLogin')
  fill_in('user_name', :with => 'amanda22')
  fill_in('user_password', :with => 'delta@453Tgf')
  fill_in('re_password', :with => 'delta@453Tgf')
  click_button('btnSave')
  click_button('Edit')
  fill_in('personal_txtEmpFirstName', :with => 'Amanda')
  fill_in('personal_txtEmpMiddleName', :with => 'Luiz')
  fill_in('personal_txtEmpLastName', :with => 'Silva')
  fill_in('personal_txtOtherID', :with => '25463')
  fill_in('personal_txtLicenNo', :with => '2576534')
  fill_in('personal_txtLicExpDate', :with => '2017-05-19')
  find(:xpath,'//*[@id="personal_optGender_1"]').click
  select('Brazil',:from =>'personal_cmbNation')
  select('Single',:from =>'personal_cmbMarital')
  fill_in('personal_DOB', :with => '1993-03-17')
  click_button('btnSave')
  click_link('Contact Details')
  click_button('Edit')
  fill_in('contact_street1', :with => 'Aimbere')
  fill_in('contact_city', :with => 'São Paulo')
  fill_in('contact_province', :with => 'São Paulo')
  fill_in('contact_emp_zipcode', :with => '05018010')
  select('Brazil',:from =>'contact_country')
  fill_in('contact_emp_hm_telephone', :with => '(11)3656-9879')
  fill_in('contact_emp_mobile', :with => '(11)97956-9248')
  fill_in('contact_emp_work_telephone', :with => '(11)3656-7890')
  fill_in('contact_emp_work_email', :with => 'teste@gmail.com')
  fill_in('contact_emp_oth_email', :with => 'nutella@gmail.com')
  click_link('Emergency Contacts')
  click_button('btnAddContact')
  fill_in('emgcontacts_name', :with => 'Alda Silva')
  fill_in('emgcontacts_relationship', :with => 'Mae')
  fill_in('emgcontacts_homePhone', :with => '(11)3656-7890')
  fill_in('emgcontacts_mobilePhone', :with => '(11)97956-9867')
  fill_in('emgcontacts_workPhone', :with => '(11)97956-9867')
  click_button('Save')
  click_link('Dependents')
  click_button('btnAddDependent')
  fill_in('dependent_name', :with => 'Alda Silva')
  select('Other',:from =>'dependent_relationshipType')
  fill_in('dependent_relationship', :with => 'Mae')
  fill_in('dependent_dateOfBirth', :with => '1993-03-17')
  click_button('Save')
  click_link('Immigration')
  click_button('btnAdd')
  fill_in('immigration_number', :with => '3652784234')
  fill_in('immigration_passport_issue_date', :with => '2000-05-19')
  fill_in('immigration_passport_expire_date', :with => '2020-02-20')
  fill_in('immigration_i9_status', :with => 'Approved')
  select('Brazil',:from =>'immigration_country')
  fill_in('immigration_i9_review_date', :with => '2018-05-17')
  fill_in('immigration_comments', :with => '1ª Lei: Um robô não pode ferir um ser humano ou, por inação, permitir que um ser humano sofra algum mal')
  click_button('Save')
  click_link('Job')
  click_button('Edit')
  select('CEO',:from =>'job_job_title')
  select('Full-Time Contract',:from =>'job_emp_status')
  select('Professionals',:from =>'job_eeo_category')
  fill_in('job_joined_date', :with => '2017-02-20')
  select('IT',:from =>'job_sub_unit')
  select('New York Sales Office',:from =>'job_location')
  fill_in('job_contract_start_date', :with => '2014-02-20')
  fill_in('job_contract_end_date', :with => '2017-02-20')
  click_button('Save')
  click_link('Salary')
  click_button('addSalary')
  select('Executive',:from =>'salary_sal_grd_code')
  fill_in('salary_salary_component', :with => '10.000,00')
  select('Weekly',:from =>'salary_payperiod_code')
  select('United States Dollar',:from =>'salary_currency_id')
  fill_in('salary_basic_salary', :with => '70000')
  fill_in('salary_comments', :with => 'Será que estou indo bem?!')
  click_button('Save')
  click_link('Report-to')
  click_button('btnAddSupervisorDetail')
  fill_in('reportto_supervisorName_empName', :with => 'Fiona Grace')
  select('Direct',:from =>'reportto_reportingMethodType')
  click_button('Save')
  click_button('btnAddSubordinateDetail')
  fill_in('reportto_subordinateName_empName', :with => 'Jasmine Morgan')
  select('Direct',:from =>'reportto_reportingMethodType')
  click_button('Save')
  click_link('Qualifications')
  click_button('addWorkExperience')
  fill_in('experience_employer', :with => 'Inmetrics')
  fill_in('experience_jobtitle', :with => 'Testes')
  fill_in('experience_from_date', :with => '2013-02-20')
  fill_in('experience_to_date', :with => '2017-02-20')
  fill_in('experience_comments', :with => '2ª Lei: Um robô deve obedecer as ordens que lhe sejam dadas por seres humanos exceto nos casos em que tais ordens entrem em conflito com a Primeira Lei.')
  click_button('Save')

end

Então(/^o cadastro do empregado e salvo$/) do

  has_xpath?('//*[@id="sectionWorkExperience"]/div[2]/script')
  #Mensagem de Salvo com Sucesso
end
